"""
Django settings for cubatram project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-patf*r7(amx9h*w+(nx^pe!eog&57a6j(g_%c40wv=2(y)4df8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['osliani.pythonanywhere.com', 'localhost']


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'import_export',
    'captcha',
    # my apps
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cubatram.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "static/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cubatram.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
    ('ru', 'Русский'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
]

# Directorio donde se guardarán los archivos de traducción (.po)
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

USE_I18N = True  # Permite usar {% trans %} en templates y habilita el middleware de idioma
USE_L10N = True  # Formatea automáticamente fechas, números, etc., según el idioma actual

# ModelTranslation
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'  # Idioma por defecto
MODELTRANSLATION_LANGUAGES = ('es', 'en', 'ru', 'fr', 'de')  # Idiomas soportados

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.privateemail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'booking@cubatram.com'
EMAIL_HOST_PASSWORD = 'booking@2023'
DEFAULT_FROM_EMAIL = 'booking@cubatram.com'
ADMIN_EMAIL = 'oslianyabel@gmail.com'

TELEGRAM_BOT_TOKEN = '8326373759:AAE9yfgiyR-xqBYFx_MB8Wkx1t0Nl7qQhaE'
TELEGRAM_CHAT_ID = '1138837437'

RECAPTCHA_PUBLIC_KEY = '6LfvzpQrAAAAAN0lMYk4ohbIxKHw7XaFaEzJkBeq'
RECAPTCHA_PRIVATE_KEY = '6LfvzpQrAAAAAEb31RyLKg8rj5epDLq8gqvMqxXO'
RECAPTCHA_DOMAIN = 'www.google.com'
